// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwmUvdvh1orv-roNE5FhC1vG4EVY0F68o',
    appId: '1:142284090464:web:6841cb57790ddd553ce705',
    messagingSenderId: '142284090464',
    projectId: 'quicknews1234',
    authDomain: 'quicknews1234.firebaseapp.com',
    storageBucket: 'quicknews1234.appspot.com',
    measurementId: 'G-75X5TQDP05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7BcuiFJGOYAYQG18fqSUglRA-yec_nM',
    appId: '1:142284090464:android:3eed7b347b77cc413ce705',
    messagingSenderId: '142284090464',
    projectId: 'quicknews1234',
    storageBucket: 'quicknews1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCawpnf5btO54QSJ4ty53r4ksad6xvR_I',
    appId: '1:142284090464:ios:1f96212ec3f55aee3ce705',
    messagingSenderId: '142284090464',
    projectId: 'quicknews1234',
    storageBucket: 'quicknews1234.appspot.com',
    iosBundleId: 'com.example.quicknews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCawpnf5btO54QSJ4ty53r4ksad6xvR_I',
    appId: '1:142284090464:ios:1f96212ec3f55aee3ce705',
    messagingSenderId: '142284090464',
    projectId: 'quicknews1234',
    storageBucket: 'quicknews1234.appspot.com',
    iosBundleId: 'com.example.quicknews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwmUvdvh1orv-roNE5FhC1vG4EVY0F68o',
    appId: '1:142284090464:web:7ed6f81a48fd71833ce705',
    messagingSenderId: '142284090464',
    projectId: 'quicknews1234',
    authDomain: 'quicknews1234.firebaseapp.com',
    storageBucket: 'quicknews1234.appspot.com',
    measurementId: 'G-D2V34917TG',
  );
}
